### ISSUE TITLE
Script can't find Meow in Cattery

### ISSUE THREAD

**Issue by modhurita** [ska-sa/meqtrees-cattery#20]
I am getting the following error:

>mitra@elwood:~/test_simulation$ ./ComputeBeamVariationMuellerMatrix.py --app-to-int --primary-beam= 'vla_L_$(xy)_$(reim).fits' 3C147-GdB-spw0+pybdsm.lsm.html a.lsm.html -f

>Reading 3C147-GdB-spw0+pybdsm.lsm.html (Tigger sky model)
Model contains 58 sources
Converting apparent fluxes to intrinsic
Traceback (most recent call last):
  File "./ComputeBeamVariationMuellerMatrix.py", line 591, in <module>
    from Cattery.Meow import Context
  File "/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Meow/__init__.py", line 47, in <module>
    from CorruptComponent import CorruptComponent
  File "/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Meow/CorruptComponent.py", line 28, in <module>
    from SkyComponent import *
  File "/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Meow/SkyComponent.py", line 29, in <module>
    from Parameterization import *
  File "/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Meow/Parameterization.py", line 30, in <module>
    import Meow
ImportError: No module named Meow

This is the python path:

>mitra@elwood:~/test_simulation$ echo $PYTHONPATH
:/home/mitra/Purr:/home/mitra/MeqTrees/meqtrees-timba/install/symlinked-release/libexec/python:.:/home/mitra/MeqTrees:/home/mitra/MeqTrees/owlcat:/home/mitra/MeqTrees/purr/Purr:/home/mitra/MeqTrees/tigger:/home/mitra/MeqTrees/pyxis:/home/mitra/MeqTrees/meqtrees-cattery::/usr/local/lofarsoft-trunk/lib/python2.7/site-packages

**Comment by SpheMakh** [comment]
I think Meow lives in Cattery. Could you try replacing line 30 in `/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Meow/Parameterization.py` with `from Cattery import Meow`

**Comment by modhurita** [comment]
Tried that, now the error message says:
  
>File "/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Meow/Parameterization.py", line 30, in <module>
    from Cattery import Meow
ImportError: cannot import name Meow
mitra@elwood:~/test_simulation$

**Comment by SpheMakh** [comment]
Oops, that's not going to work since Parameterization.py is already in Meow.   
are you able to run:  `python -c from Cattery.Meow import Context` ?

**Comment by modhurita** [comment]
No:

>mitra@elwood:~/test_simulation$ python -c "from Cattery.Meow import Context" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cattery.Meow

**Comment by SpheMakh** [comment]
Something might be wrong with your meqtrees installation. If you have included meqtrees-cattery in your PYTHONPATH, then you should be able to import Cattery.Meow.

**Comment by modhurita** [comment]
This has been solved by changing PYTHONPATH in meqtrees-init.sh to:

`export PYTHONPATH=$MQT_PATH:$MQT_PATH/owlcat:$MQT_PATH/purr/Purr:$MQT_PATH/tigger:$MQT_PATH/pyxis:$MQT_PATH/meqtrees-cattery:$PYTHONPATH`

(the Cattery-related part above was `$MQT_PATH/meqtrees-cattery/Cattery` earlier)
