### ISSUE TITLE
Selecting an interferometer subset for turbo-sim

### ISSUE THREAD

**Issue by TariqBlecher** [ska-sa/meqtrees-cattery#24]
So I've tried many different combinations of syntaxes for excluding Antennas in turbo-sim via pyxis: -name*,-name-*,-number*..Even for the inputs which don't raise an error, the excluded antenna is still in fact included. I test this by running a np.where(ANTENNA1==relevant_number_of antenna)

**Comment by SpheMakh** [comment]
Could you clarify what you are trying to achieve. Do you want to exclude some antennas for a simulation, or do you want some antennas in the MS never to be used? If you want the former, then `turbo-sim` should do the trick, if you want the latter, then `flagms.py` is what you want to use.

**Comment by TariqBlecher** [comment]
ohh wait, does excluding an antenna, say with "-SMT*", flag the data taken
by SMT or does it delete the rows of the data taking by SMT?

**Comment by SpheMakh** [comment]
If I understand you correctly; neither of those things happen. When you exclude antennas via `interferometers to use` in `turbo-sim`, `turbo-sim` just excludes those antennas for that simulation. It neither flags or deletes anything.

**Comment by TariqBlecher** [comment]
turbo-sim should be able to do it but in practice it seems to ignore the
interferometers to use string and default to all. So if I check the log of
the sim it will show the string I passed but when I check the MS the
excluded stations were in fact included

**Comment by TariqBlecher** [comment]
ohh  I see an error in my test procedure

**Comment by TariqBlecher** [comment]
Ok ok I was looking in the wrong place: So to exclude an antenna this works : -(ANTENNA NAME) - *
