### ISSUE TITLE
stefcal number of valid baselines criterion

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/meqtrees-cattery#29]
Stefcal bails out if it doesn't have at least ten valid baselines from which to determine a solution. Can this be relaxed? My input MS only has 14 to begin with.

**Comment by o-smirnov** [comment]
Yeah it's a bit of a capricious limitation to be honest. Can you quickly
change Calico/OMS/StefCal/StefCal.py:494 to read:
```
    min_baselines_for_solution = len(solvable_antennas)+1;
```
