### ISSUE TITLE
Fits file lock

### ISSUE THREAD

**Issue by TariqBlecher** [ska-sa/meqtrees-cattery#30]
ever seen this error? I'm feeding in a fitsfile to turbo-sim, somehow meqtrees thinks that the fits file is locked but its not being used by another process

wcsfix ERROR, status returns: (-1, -1, 0, 0, 7, -1)

wcsset ERROR 7:
### Job terminated with exception:
Traceback (most recent call last):
  File "/usr/local/meqtrees/Timba/install/symlinked-release/bin/meqtree-pipeliner.py", line 157, in <module>
   .....
RuntimeError: cannot release un-acquired lock

**Comment by SpheMakh** [comment]
Sadly MeqTrees is very particular about the FITS files it accepts as sky models. The FITS file has to have this structure, `RA,DEC,STOKES,FREQ`.  What is the output of `fitstool.py -H <your fits file> `, also could you  post the full error message.

**Comment by SpheMakh** [comment]
TIP: If you want to turn a FITS a file into visibilities, **lwimager** is the tool you want to use. see `im.lwimager.predict_vis()` in pyxis
