### ISSUE TITLE
Pointing error passed through turbosim via pyxis sets all visibilities to zero

### ISSUE THREAD

**Issue by TariqBlecher** [ska-sa/meqtrees-cattery#41]
Pointing error passed through turbosim via pyxis sets all visibilities to zero. This happens even if the pointing error is set equal to 0.

A typical Pyxis output:

```
### Starting meqserver
### Attaching to configuration file tdlconf.profiles
### Loading config section turbo-sim
### Setting option oms_pointing_errors.pe_m.values_str=0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
### Setting option oms_pointing_errors.pe_l.values_str=0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
### Setting option analytic_beams.circular_aperture_beam.bf=1.0
### Setting option ms_sel.msname=centralpointSgrA.MS
### Setting option me.e_enable=1
### Setting option me.e_module=Siamese_OMS_analytic_beams
### Setting option oms_pointing_errors.pe_l.error_model=ListOfValues
### Setting option me.epe_enable=1
### Setting option fitsimage_sky.image_filename=input/centralpointSgrA/centralpointSgrA.fits
### Setting option oms_pointing_errors.station_subset=all
### Setting option model_type=use_circular_aperture
### Setting option analytic_beams.circular_aperture_beam.dish_sizes=25 30 32 25 30 25 15 10
### Setting option oms_pointing_errors.pe_m.error_model=ListOfValues
### Compiling turbo-sim.py
```

**Comment by IanHeywood** [comment]
Does this happen if you use e.g. one of the gridded sky models instead of the FITS image?

I think last time I tried the FITS sky model option in MeqTrees it was being weird.

**Comment by TariqBlecher** [comment]
Okay, Tried with a gridded sky model and now more error information is given. Seems like the strings are not being parsed properly..

I'm passing lists through the options keyword in turbo-sim with this syntax.

options["analytic_beams.circular_aperture_beam.dish_sizes"] = "25\\ 30\\ 32\\ 25\\ 30\\ 25\\ 15\\ 10"

______________________________________________________________________________
2.0Gb tdlc(Compile.py:287:run_forest_definition): exception defining forest from TDL file: turbo-sim.py
Traceback (most recent call last):
  File "/usr/local/meqtrees/Timba/install/symlinked-release/libexec/python/Timba/TDL/Compile.py", line 224, in run_forest_definition
    define_func(ns,**args);
  File "turbo-sim.py", line 185, in _define_forest
    output = meqmaker.make_predict_tree(ns,uvdata=model_spigots);
  File "/usr/local/meqtrees/Cattery/Meow/TensorMeqMaker.py", line 215, in make_predict_tree
    basenodes = self._get_skyjones_tensor(ns,jt,stations,source_groups,other_sources=other_sources);
  File "/usr/local/meqtrees/Cattery/Meow/TensorMeqMaker.py", line 84, in _get_skyjones_tensor
    dlm = self._get_pointing_error_nodes(ns,jt,stations);
  File "/usr/local/meqtrees/Cattery/Meow/MeqMaker.py", line 679, in _get_pointing_error_nodes
    inspectors=inspectors,meqmaker=self);
  File "/usr/local/meqtrees/Cattery/Siamese/OMS/oms_pointing_errors.py", line 54, in compute_pointings
    node_maker1(ns.l(p),station=p,axis='l');
  File "/usr/local/meqtrees/Cattery/Siamese/OMS/ErrorGens.py", line 87, in make_node
    self.values = map(float,self.values_str.split(" "));
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "/usr/local/meqtrees/Timba/install/symlinked-release/bin/meqtree-pipeliner.py", line 147, in <module>
    module,ns,msg = Compile.compile_file(mqs,script,config=section);
  File "/usr/local/meqtrees/Timba/install/symlinked-release/libexec/python/Timba/TDL/Compile.py", line 303, in compile_file
    predef_args=predef_args,define_args=define_args,postdef_args=postdef_args);
  File "/usr/local/meqtrees/Timba/install/symlinked-release/libexec/python/Timba/TDL/Compile.py", line 293, in run_forest_definition
    raise TDL.CumulativeError(*ns.GetErrors());
CumulativeError: 
 [  1] could not convert string to float: 
2.0Gb meqserver(meqserver.py:288:stop_default_mqs): meqserver not exited yet, waiting another 10 seconds
### Starting meqserver
### Attaching to configuration file tdlconf.profiles
### Loading config section turbo-sim
### Setting option gridded_sky.source_pol=0
### Setting option analytic_beams.circular_aperture_beam.dish_sizes=25 30 32 25 30 25 15 10
### Setting option me.sky.tiggerskymodel=0
### Setting option gridded_sky.grid_m0=0
### Setting option oms_pointing_errors.pe_l.error_model=ListOfValues
### Setting option gridded_sky.grid_step=1e-07
### Setting option me.sky.siamese_oms_gridded_sky=1
### Setting option gridded_sky.model_func=cross_model
### Setting option analytic_beams.circular_aperture_beam.bf=1.0
### Setting option me.e_enable=1
### Setting option me.epe_enable=1
### Setting option me.sky.siamese_oms_fitsimage_sky=0
### Setting option me.sky.siamese_oms_transient_sky=0
### Setting option gridded_sky.source_spi_2=None
### Setting option oms_pointing_errors.pe_m.values_str=0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
### Setting option ms_sel.msname=centralpointSgrA.MS
### Setting option me.sky.siamese_agw_azel_sky=0
### Setting option me.e_module=Siamese_OMS_analytic_beams
### Setting option gridded_sky.grid_l0=0
### Setting option gridded_sky.source_flux=1
### Setting option gridded_sky.source_freq0=None
### Setting option gridded_sky.source_spi=None
### Setting option gridded_sky.center_source_flux=1
### Setting option gridded_sky.grid_size=1
### Setting option gridded_sky.source_type=point
### Setting option oms_pointing_errors.station_subset=all
### Setting option model_type=use_circular_aperture
### Setting option oms_pointing_errors.pe_l.values_str=0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
### Setting option oms_pointing_errors.pe_m.error_model=ListOfValues
### Compiling turbo-sim.py

**Comment by o-smirnov** [comment]
Strange that you don't get the same error in the first case! @TariqBlecher could you please give me a test case? As I requested earlier -- make a subdirectory somewhere, and make a copy of the MS and the pipeline, so I can just run a command and see it blow up for myself.

On an unrelated note: when you paste output into an issue, could you please surround it with triple-backquotes so that it's formatted properly? Very hard to read it otherwise. I have edited your previous posts to include the triple backquotes.

Also, I realized I didn't explain one thing properly: if you're using a FITS image sky model, pointing error does not work (in fact the primary beam does not work). The current PE models in the Cattery will only work with component models (such as gridded skies, or Tigger LSMs). Are such LSMs sufficient for you to do your pointing error investigation, or must you have images too? In the latter case we can probably cobble together something quick using DDFacet, @SpheMakh already has it predicting visibilities, and I can implement pointing errors fairly quickly.

**Comment by rdeane** [comment]
Parametric models should be fine for the MeqSilhouette paper 1 pointing error analysis. It's a small input image, so we can just convert the pixel values into point sources with the same amplitude and read in as a Tigger LSM. If we want to do a more robust analysis further down the road, it would be nice to be able to do pointing error on FITS images. This would be particularly if we do a high enough resolution version to resolve the ISM diffractive scale.

**Comment by IanHeywood** [comment]
You can also down the OSKAR2 route if your model image isn't too big, and just decompose it into a components list.

**Comment by TariqBlecher** [comment]
Oleg I have already sent you a link to the subdirectory for testing.

Thanks for the heads up on formatting. 

A parametrised Gaussian should be fine for this investigation but let's put in an error message which pops up when primary beam effects are enabled but the sky model is a fits file.
