### ISSUE TITLE
travis build appears to be broken

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/meqtrees-cattery#42]

**Comment by gijzelaerr** [comment]
Travis is not broken, I fixed it months ago:

https://github.com/ska-sa/meqtrees-cattery/commits/f1df47d191d5bd5cb3c06a5f7aaeca2a34388abd/.travis.yml

you've applied the fix on an old checkout with a broken travis file:

https://github.com/ska-sa/meqtrees-cattery/compare/issue-32...master

I think If you `merge rebase` the master changes to your branch it should work.

**Comment by gijzelaerr** [comment]
which I did. It now fails on an other error which i don't know what it is.
