### ISSUE TITLE
FITS header requirements for turbo-sim

### ISSUE THREAD

**Issue by TariqBlecher** [ska-sa/meqtrees-cattery#43]
I cannot find any documentation detailing the FITS header requirements when loading a FITS file through
 meqtrees-cattery/Cattery/Siamese/OMS/fitsimage_sky.py .   

For example, the CUNIT1 parameter. Which units does turbo-sim understand (deg/DEG/degrees/rad/RAD/radian) ?

**Comment by SpheMakh** [comment]
Your FITS image needs to have four axes with ra,dec,stokes,freq
corresponding to naxis1,2,3,4

Use fitstool.py (part of owlcat) to manipulate FITS axes.
