### ISSUE TITLE
calico-stefcal.py: crashes when "corrected data minus DDS" requested

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/meqtrees-cattery#49]
I'm assuming that requesting "corrected data minus DDS" as the visibility output provides corrected data but subtracts only the components which are subjected to dEs, which is *exactly* what I need.

However when I run this it bails out with the following:

```
741.61 gainopts(StefCal.py:879:get_result): saving solutions
741.61 gainopts(GainOpts.py:253:flush_tables): saved 2 gain set(s) to diffgain.cp
741.62 gainopts(GainOpts.py:253:flush_tables): saved 1 gain set(s) to gain.cp
741.62 gainopts(StefCal.py:905:get_result): checking flagging
741.68 gainopts(StefCal.py:918:get_result): 0.00% (40300/5959200) data points were flagged in the stefcal process. Can take.
saving global gain G
saving global gain dE:A220
saving global gain dE:B040
741.73 gainopts(StefCal.py:1009:get_result): computing result
Traceback (most recent call last):
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/StefCal.py", line 1037, in get_result
    for d,m in zip(out,corr[pq]):
TypeError: list indices must be integers, not tuple
```

I've tried a few different scenarios, all of which were completed successfully with either a "corrected data" or "corrected residuals" request.

**Comment by o-smirnov** [comment]
I think this is an easy fix. Can you check out the ``issue-49`` branch and try again? Or just fix your local copy, it's literally a matter of deleting four characters as per [this commit](https://github.com/ska-sa/meqtrees-cattery/commit/f18a110cd3b22ddf61191740c2d59e3a12a9517b).

**Comment by IanHeywood** [comment]
Fixed! Thanks chief.

Can you please confirm that the behaviour I've assumed is what the option actually does? The help bubble in the GUI is the one from calico-wsrt-tens.py with slightly different options. I'm happy to re-write it for calico-stefcal.py in exchange for this fix. :)

**Comment by o-smirnov** [comment]
Yes, your assumption is entirely correct. The help bubble was indeed a victim of cut-and-paste... I've committed a fix for that as well.
