### ISSUE TITLE
calico-stefcal.py: sometimes the gain pickles are unreadable

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/meqtrees-cattery#50]
Sometimes when I try to plot the contents of a gain pickle I get the following error just from trying to read it. Not too familiar with the internal structure of pickles, but I guess it's got a key in the header that isn't used or something.

```
     26 def getgains(gainpickle):
---> 27         gaindict = pickle.load(open(gainpickle,'r'))
     28         gains = gaindict['gains']['G']['solutions']
     29         return gains

AttributeError: 'module' object has no attribute 'MeqVells'
```

I've attached two examples, test.cp is readable, test2.cp is not, the only difference as far as I can tell is that I halved the solution interval for the latter. By the way the above example has

```
import cPickle as pickle
```

but pickle doesn't read them either. The inspector plot shows that solutions are being generated in  both cases, and there are not other obvious errors that differentiate the runs.

**Comment by IanHeywood** [comment]
[test.cp.gz](https://github.com/ska-sa/meqtrees-cattery/files/476245/test.cp.gz)
[test2.cp.gz](https://github.com/ska-sa/meqtrees-cattery/files/476244/test2.cp.gz)

**Comment by o-smirnov** [comment]
That error is normally addressed by the completely non-obvious statement

```
import Timba.Meq.meq
```

(This makes the internal Meq-types visible to Python... sigh... if I was designing this thing today, I'd make it so much simpler...)

Could you quickly check if that solves the problem?

**Comment by o-smirnov** [comment]
Yep, both files read fine for me after the import above has been done. The mystery is how ``test.cp`` is readable ***without*** the import, but somehow it is!

**Comment by IanHeywood** [comment]
I'm happy to conserve the number of mysteries in this case, creating one I'll hopefully never have to worry about in exchange for solving one that was causing trouble. Cheers.

**Comment by o-smirnov** [comment]
Yeah indeed, too much shit that doesn't work when it should for us to worry about shit that works when it shouldn't...
