### ISSUE TITLE
handle MSs with missing reference antenna

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/meqtrees-cattery#51]

**Comment by IanHeywood** [comment]
Slightly off topic but I'll ask here anyway: how does Stefcal deal with reference antennas? No matter what I set as the reference antenna the phases for that antenna in the solutions are never flat...

**Comment by o-smirnov** [comment]
@IanHeywood it doesn't, not in the usual sense. The reference antenna, in this context, is just used for UVW decomposition. StefCal just lets the phases float, essentially.

**Comment by ludwigschwardt** [comment]
That's interesting... In our implementations we tend to renormalise within
each StefCal iteration so that the reference antenna's phase remains zero.
I recall it helping the algorithm to converge. Something to reconsider then.

**Comment by o-smirnov** [comment]
That's an excellent idea! I don't know why it would help convergence though?
