### ISSUE TITLE
bitwise or assignment causes crash

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/meqtrees-cattery#66]
```
node 'VisDataMux': execute() failed: ufunc 'bitwise_or' output (typecode 'l') could not be coerced to provided output parameter (typecode '?') according to the casting rule ''same_kind'' (return code 0x810021)
```

The offending line is 1396 in Calico/OMS/StefCal/StefCal.py
```
  fmask |= gainflags.get(pq[1],0)
```

Which suggests the type being compared are not the same. In fact, changing this line to

```
  fmask =  fmask|gainflags.get(pq[1],0)
```

fixes the problem. But I think its better to figure out why they are different to begin with

**Comment by SpheMakh** [comment]
It may be related to this: https://github.com/numpy/numpy/issues/6464

**Comment by bennahugo** [comment]
The two lines shouldn't make a difference I think we need to dig a bit deeper. I have a full log on the new jenkins instance on ike.

**Comment by bennahugo** [comment]
Minimal example:
```
In [1]: import numpy as np

In [2]: a = np.ones([5], dtype=np.int)

In [3]: b = np.ones([5], dtype=np.int) * 2

In [4]: c = np.zeros([5], dtype=np.int)

In [5]: d = a | b

In [6]: d
Out[6]: array([3, 3, 3, 3, 3])

In [7]: c |= a

In [8]: c |= b

In [9]: c
Out[9]: array([3, 3, 3, 3, 3])
```
Something must not be an int  here

**Comment by bennahugo** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.typename.html

Okay seems the lvalue is a bool (typecode: "?") and the rvalue is a longint (typecode: "l")
https://github.com/ska-sa/meqtrees-cattery/blob/master/Cattery/Calico/OMS/StefCal/StefCal.py#L1395

So the solver returns a bool (int8) for the lower and int64 for the upper gain amplitude bounds. Obviously the other way around in this particular case would be okay (as long as the lvalue has a type larger than the rvalue). I can reproduce with a minimal example
```
In [46]:  a = np.ones([5], dtype=np.bool)

In [47]: a |= (np.ones([5], dtype=np.long) * 2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-b7c055620a39> in <module>()
----> 1 a |= (np.ones([5], dtype=np.long) * 2)

TypeError: ufunc 'bitwise_or' output (typecode 'l') could not be coerced to provided output parameter (typecode '?') according to the casting rule ''same_kind''

```

**Comment by bennahugo** [comment]
@o-smirnov 
https://github.com/ska-sa/meqtrees-cattery/blob/50127050157d997ba71a4117f5afea2cd36e75a3/Cattery/Calico/OMS/StefCal/Gain2x2.py#L290

Mask is a bool (int8) and we are not bit packing the flags so why are we using bitwise or and not np.logical_or?

**Comment by bennahugo** [comment]
The only place where I can see where two different types can be introduced is here:
```
      if numpy.any(mask):
        if p in self.gainflags:
          self.gainflags[p] |= mask;
        else:
          self.gainflags[p] = mask;
```
initially mask is bool[] so gainflags will be bool[]  and if be some mechanism gainflags are cast to long mask will be cast to long as well and things will be long[] from that point forward, so some gainflags[p] may be bool[] and others long[]

**Comment by o-smirnov** [comment]
Just a dumb typo. These flags are meant to be boolean. (There are bitwise flags elsewhere in the code, but not here). Because of [this](https://github.com/ska-sa/meqtrees-cattery/commit/3703c79d619dc5d748df0478902f096255c70ffe), they occasionally ended up as 0 instead of ``False``. Doing ``|= 0`` on a boolean array is not kosher.
