### ISSUE TITLE
GainDiag

### ISSUE THREAD

**Issue by radiosky-abhik** [ska-sa/meqtrees-cattery#70]
Hello Guys,
                    It seems that there is some issues with the GainDiag option in the meqtrees that is not going through when I try to use it to self-calibrate a 325 MHz GMRT data in Stimela. I am getting the following error:

[log-calibrator_Gjones_subtract_lsm3.txt](https://github.com/ska-sa/meqtrees-cattery/files/912499/log-calibrator_Gjones_subtract_lsm3.txt)

**Comment by SpheMakh** [comment]
Fixed in #71
